Fn arg last comma removed
iomentum/cargo-breaking pull request #13
Opened 2021-07-09 12:44 UTC by YannBonaudo

2021-07-09 12:55 UTC, scrabsha approved these changes

2021-07-09 13:49 UTC, cbonaudo commented on tests/function.rs
> +        },
If we try "pub fn a(a: t, b: t, c: t) {}" won't it remove the "t" ? 
if not it could be nice to have a test to show it

2021-07-10 09:29 UTC, cbonaudo approved these changes

2021-07-10 12:53 UTC, scrabsha requested changes

2021-07-10 12:53 UTC, scrabsha commented on tests/function.rs
> +}
A better (and perhaps more explicit) way to ensure that the last argument is still handled is to change its type, and assert that a function modification is reported. This way, we're sure we don't remove arguments from all the functions that have one or more argument.

2021-07-12 07:07 UTC, scrabsha approved these changes

2021-07-12 07:09 UTC, merged