Use nightly toolchain for the CI
iomentum/cargo-breaking pull request #26
Opened 2021-07-26 13:23 UTC by yozhgoor

2021-07-26 13:25 UTC, cbonaudo approved these changes

2021-07-26 15:56 UTC, o0Ignition0o approved these changes

2021-07-27 07:38 UTC, scrabsha requested changes

2021-07-27 07:38 UTC, scrabsha commented on .github/workflows/main.yml
> +          components: rustfmt, clippy
In order to get access to the Rustc API, we need to install a few components, as defined [in the docs](https://github.com/iomentum/cargo-breaking/blob/a381567ed4ab4ebc22d9be999977c759f314b2b9/book/src/1_foreword.md).

This is needed for each CI job unfortunately.

2021-07-27 07:41 UTC, scrabsha commented
I forgot to mention it in the PR review comment, you need to request merge to the [`rustc-backend`] branch (instead of main).

[`rustc-backend`]: https://github.com/iomentum/cargo-breaking/tree/rustc-backend

2021-07-27 13:17 UTC, yozhgoor commented
> I forgot to mention it in the PR review comment, you need to request merge to the [`rustc-backend`](https://github.com/iomentum/cargo-breaking/tree/rustc-backend) branch (instead of main).

I don't know why but the CI don't trigger in the `rustc-backend` branch, i will test on main and switch when i'm sure it's ok

2021-07-28 07:45 UTC, scrabsha approved these changes

2021-08-05 17:34 UTC, merged