Add glue generation code
iomentum/cargo-breaking pull request #27
Opened 2021-07-30 07:47 UTC by scrabsha

The idea is that we have to generate a temporary crate, with very little code in it, with has two dependencies: the previous and the next crate we are about to analyze.

2021-08-01 09:31 UTC, scrabsha commented on src/cli/standard_compiler.rs
> +    fn ask_to_rustc(&self) -> AnyResult<String> {
This one can be renamed to `fallback_to_rustc`, as it can theoretically handle any invocation of rustc.

2021-08-01 09:31 UTC, scrabsha commented on src/cli/standard_compiler.rs
> +            .output()
We could use `status` here, so that we can save us from returning what rustc printed on stdout

2021-08-03 17:04 UTC, o0Ignition0o requested changes
This is a very solid PR!

I really love the comments you've put here and there, explaining why things look the way they do. It shows readers you care for them, and we can feel it, and it's super appreciated! 😍 

I think you're on the right track, and we can polish this a bit further in order to get smooth code that flows nicely.

Regardless you did a really great job, cheer! 🎉

2021-08-03 17:08 UTC, cbonaudo approved these changes

2021-08-05 21:44 UTC, scrabsha commented on src/cli.rs
> +                process::exit(101);
I tried to refactor the way the `StandardCompiler` is created and run in commit [af3f35c](https://github.com/iomentum/cargo-breaking/pull/27/commits/af3f35c99e91f406928151177489c63d68736f1d). Do you think it makes the thing clearer?

This commit also adds a comment about why the seemingly-unnecessary clone is performed in `StandardCompiler::run`. Is it good enough?

2021-08-06 20:58 UTC, scrabsha commented on src/cli/standard_compiler.rs
> +            .map_err(|e| anyhow!("{:?}", e))
[`anyhow::Error::new`](https://docs.rs/anyhow/1.0.42/anyhow/struct.Error.html#method.new) may be prefered here.

2021-08-06 20:58 UTC, scrabsha commented on src/cli/standard_compiler.rs
> +            .map_err(|e| anyhow!("{:?}", e))
[`anyhow::Error::new`](https://docs.rs/anyhow/1.0.42/anyhow/struct.Error.html#method.new) may be prefered here.

2021-08-06 20:58 UTC, scrabsha commented on src/cli.rs
> +    /// as what was provided when the program was invoked exits the process.
A world is missing  in that sentence (`then`).

2021-08-11 13:27 UTC, o0Ignition0o approved these changes

2021-08-11 13:32 UTC, merged